### ISSUE TITLE
Cant find any panel

### ISSUE THREAD

**Issue by hushengkai** [LeonidasWhite/BCRYExporter#1]
First of all, thank you for updating the plug-in, which has helped a lot.
I have now imported the plug-in, but I can't find any visual interface. I can find a separate feature in the operator search (F3), but I can't find any interface.

**Comment by chrissoe** [comment]
Had the same problem. You can just expand the sidebar using the shortcut "N" or that super tiny arrow on the top right main window in Blender. It will appear there.

![image](https://user-images.githubusercontent.com/5297913/61870722-18e34b80-aedf-11e9-96e7-a474f0b76d51.png)

**Comment by hushengkai** [comment]
Thank You

**Comment by hushengkai** [comment]
Thank You
