### ISSUE TITLE
Branches export error

### ISSUE THREAD

**Issue by brickengineer** [LeonidasWhite/BCRYExporter#2]
Hey, thanks for updating BCryExporter for Blender 2.80. This is really great.
Issues:
The branch export process reports errors. I have provided a project of touch bending for testing below. 
[bush01_final.zip](https://github.com/LeonidasWhite/BCRYExporter/files/3465012/bush01_final.zip)

**Comment by LeonidasWhite** [comment]
@brickengineer Thanks for reporting. I'll be investigate soon.

**Comment by LeonidasWhite** [comment]
Okay. I fixed errors and tested.
1) Don't use much branch. Some leaves are generated without branch. But if delete half of branches then it fix all problems.
2) Use double underline to split material name or use add material properties.
[bush01_final.zip](https://github.com/LeonidasWhite/BCRYExporter/files/3468240/bush01_final.zip)
I fixed all in your file. Try and tell me if something wrong or if be another errors.

P.S. Please, switch to development branch for download fix.

**Comment by LeonidasWhite** [comment]
@brickengineer I added another examples from official documentation. Question to you: Your bush looks simple for understanding how works branch. Can I add your file as example to repository?

**Comment by brickengineer** [comment]
> @brickengineer I added another examples from official documentation. Question to you: Your bush looks simple for understanding how works branch. Can I add your file as example to repository?

Yes, feel free to use it. 

As I tested in 2.79 version with BCry plugin, the project file I posted is quite fine and could be exported without errors. It also works correctly in Cryengine for touch bending effect. And branch really doesn't need to be child of proxy as I tested. (as long as player get into the proxy, the branch is automatically activated). So I guess there might also be some other causes that result in "too many branches" problem.

**Comment by LeonidasWhite** [comment]
> And branch really doesn't need to be child of proxy as I tested. (as long as player get into the proxy, the branch is automatically activated).

Yeah, you are right. I hastened with conclusions. But as parent it work too. In official 3ds_max examples the branches and proxy are a child.
I think in this case will be better to manipulate with object as rotate, translate... etc. Or no?

> Yes, feel free to use it.

Thanks

**Comment by LeonidasWhite** [comment]
> So I guess there might also be some other causes that result in "too many branches" problem.

Nine branches which you created works fine. But one leaf was without branches. I was try to rotate/translate/scale object or leaf and it didn't help to fix that. And only when I deleted half (perhaps it would be enough to remove a couple of branches) then all the leaves began to work as they should. Hope this will help you.

**Comment by brickengineer** [comment]
> > So I guess there might also be some other causes that result in "too many branches" problem.
> 
> Nine branches which you created works fine. But one leaf was without branches. I was try to rotate/translate/scale object or leaf and it didn't help to fix that. And only when I deleted half (perhaps it would be enough to remove a couple of branches) then all the leaves began to work as they should. Hope this is help you.

 As I tested and watched carefully, there IS one leaf doesn't work... Perhaps too many branches. Thanks for reminding me.
