### ISSUE TITLE
[Vertex Colors] Export errors.

### ISSUE THREAD

**Issue by brickengineer** [LeonidasWhite/BCRYExporter#3]
Hey, it's me again. I found that BCRYExporter can not export vertex color info correctly with Blender 2.80 (I am using your lasted github version). As I tested, the old version for 2.79 works fine. FBX export also works fine.
I found this issue when trying to export a plane mesh with vertex painting so it could be used as cloth mesh (common cloth not VCloth). But cloth behaves wrong which indicate vertex color errors. 
I believe this error will also influce other vertex color related assets such as detailed bending.
Two blender files are provided below for your testing convience.

[vertex_color_test.zip](https://github.com/LeonidasWhite/BCRYExporter/files/3771849/vertex_color_test.zip)

**Comment by LeonidasWhite** [comment]
@brickengineer Thanks. I'll investigate soon.

**Comment by LeonidasWhite** [comment]
@brickengineer  Hi! I'm looked at this problem and I can say that the problem is in sorting indexes. The same problem is in exporting bones. In fact that working only stable Blender 2.79b . The newest version 2.79 from git (builder.blender.org) on the moment when it available - export broken too. I'll try to fix, but I'm not promise that be quickly.

**Comment by LeonidasWhite** [comment]
@brickengineer I fixed it. The vertex color data from bmesh in 2.79 is Color (as Vector3), but in 2.80 it is Vector4. Can I ask you to test fix? Please, got fix from development branch.

**Comment by brickengineer** [comment]
Great! It works as expected now.
_By the way, the 2.8 ver. file I send you seems to have a little problem. It seems the top line vertices has been painted black but few of them act like they are paint white after export (not matter BCRY or FBX). Use "Vertex Selection" and repaint them will solve this. It might be a belnder bug. Just to let you know in case it leads to misunderstanding._
